### ISSUE TITLE
Need to update supported markets in the plugin description

### ISSUE THREAD

**Issue by sancho21** [AzrizHaziq/tradingview-syariah-indicator#41]
So that people aware that there are other countries supported. Location: Firefox plugin description, Chrome plugin description, Github project description.

![image](https://user-images.githubusercontent.com/435505/168455844-eca29053-87f8-4fcb-a4ef-9594bb5cc3b0.png)

**Comment by AzrizHaziq** [comment]
updated tq

![image](https://user-images.githubusercontent.com/9023187/168459735-2a7ccf81-80db-4dce-9d89-a806fc660b31.png)
