### ISSUE TITLE
Indicator not visible when there's a pane on top

### ISSUE THREAD

**Issue by sancho21** [AzrizHaziq/tradingview-syariah-indicator#45]
![image](https://user-images.githubusercontent.com/435505/179117679-ea65c4e6-1dd3-4e0f-86bd-0be112b7a3c0.png)

When using a pane on top of the primary chart pane, the halal logo is gone

**Comment by sancho21** [comment]
If the pane/region hosting TL's RS Line is removed, then the logo will be back

**Comment by AzrizHaziq** [comment]
https://github.com/AzrizHaziq/tradingview-syariah-indicator/pull/49
