### ISSUE TITLE
Jumpy navigation in stock screener

### ISSUE THREAD

**Issue by sancho21** [AzrizHaziq/tradingview-syariah-indicator#47]
When using down button to loop over the result list, the non-sharia ones can still be navigated to (even though not highlighted). So, it's confusing and not convenient.

**Comment by AzrizHaziq** [comment]
This issue is somewhat related to https://github.com/AzrizHaziq/tradingview-syariah-indicator/issues/46, as at the moment how we use css to hide/display the stock item. 

This surely can be achieve by using JS if else, but will make the performance slow as some user report previously

**Comment by AzrizHaziq** [comment]
Sorry accidentaly close this issue. Please reopen it if found alternative solution (avoid for loop)
