### ISSUE TITLE
shariah indicator not shown on chart

### ISSUE THREAD

**Issue by azlankenali** [AzrizHaziq/tradingview-syariah-indicator#57]
I'm using chrome and firefox. On screener have indicator shown but not on chart

**Comment by AzrizHaziq** [comment]
Hi @azlankenali , can help share more detail information like? the urls, screenshot, TSI verson, did you modify data source and etc. Tq

**Comment by azlankenali** [comment]
Firefox:

[image: image.png]

[image: image.png]

Chrome:
[image: image.png]

[image: image.png]

How to see TSI version? I didn't change the dataset. Don't know where the
dataset is.

Regards,
Mohd Azlan bin Kenali

**Comment by AzrizHaziq** [comment]
no detail info

**Comment by sancho21** [comment]
I think this is a valid issue 
![image](https://user-images.githubusercontent.com/435505/213345042-b5279af2-c4eb-47e8-90b7-4a9f3afd7828.png)

Should I raise this as multiwindow issue?

**Comment by azlankenali** [comment]
yes

**Comment by AzrizHaziq** [comment]
yes i'm aware of this, it just that im just using free account hence dont know how the DOM is.

**Comment by azlankenali** [comment]
any way I can help to capture DOM?
if you can advise the step I can help to assists. I can whatsapp / telegram
the image/DOM


Regards,
Mohd Azlan bin Kenali

**Comment by AzrizHaziq** [comment]
sure can help all the DOM part. 
However, my concern is, if tradingview constantly update on their side, it will break the code again and again. And i will also have to ping anyone asking the new DOM again as well, which will consume my time.

**Comment by azlankenali** [comment]
if you can guide me, i can learn and try do the fixing. i now a bit about
programming

**Comment by sancho21** [comment]
I've made the ticket to track this https://github.com/AzrizHaziq/tradingview-syariah-indicator/issues/58

**Comment by AzrizHaziq** [comment]
@azlankenali you can play around the chart page [here](https://github.com/AzrizHaziq/tradingview-syariah-indicator/blob/master/packages/extension/src/page/chart.ts) 

here the guide to get started https://tsi.azrizhaziq.com/dev
